# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Hexdumper
version:      1.3
version_from: lib/Data/Hexdumper.pm
installdirs:  site
requires:
    Test::More:                    0.65

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
